import streamlit as st
import streamlit.components.v1 as components
from data.mock_orders import get_order_ids
from agents.orchestrator import run_full_investigation

BRAND_NAVY = "#041e42"


def _copy_to_clipboard_button(text):
    escaped = text.replace("\\", "\\\\").replace("`", "\\`").replace("$", "\\$")
    components.html(
        f"""
        <button onclick="copyToClipboard()" id="copyBtn"
            style="padding:10px 24px;background:{BRAND_NAVY};color:white;border:none;border-radius:8px;
                   cursor:pointer;font-size:14px;font-weight:600;width:100%;font-family:Inter,sans-serif;
                   letter-spacing:0.3px;transition:all 0.2s ease;">
            Copy to Clipboard
        </button>
        <script>
        function copyToClipboard() {{
            const text = `{escaped}`;
            navigator.clipboard.writeText(text).then(() => {{
                document.getElementById('copyBtn').textContent = 'Copied!';
                document.getElementById('copyBtn').style.background = '#2e8b57';
                setTimeout(() => {{
                    document.getElementById('copyBtn').textContent = 'Copy to Clipboard';
                    document.getElementById('copyBtn').style.background = '{BRAND_NAVY}';
                }}, 2000);
            }}).catch(() => {{
                const ta = document.createElement('textarea');
                ta.value = text;
                document.body.appendChild(ta);
                ta.select();
                document.execCommand('copy');
                document.body.removeChild(ta);
                document.getElementById('copyBtn').textContent = 'Copied!';
                document.getElementById('copyBtn').style.background = '#2e8b57';
                setTimeout(() => {{
                    document.getElementById('copyBtn').textContent = 'Copy to Clipboard';
                    document.getElementById('copyBtn').style.background = '{BRAND_NAVY}';
                }}, 2000);
            }});
        }}
        </script>
        """,
        height=50
    )


def render():
    st.markdown("## Customer Response Generator")
    st.caption("AI-generated customer-ready communication for Electrolux order issues")

    col1, col2 = st.columns([2, 1])
    with col1:
        order_id = st.selectbox(
            "Select Order ID",
            options=[""] + get_order_ids(),
            format_func=lambda x: "-- Select an Order ID --" if x == "" else x,
            key="cust_resp_order_id"
        )
    with col2:
        st.write("")
        st.write("")
        generate = st.button("Generate Response", type="primary", disabled=not order_id, use_container_width=True)

    if generate and order_id:
        with st.spinner("Analyzing order and generating customer response..."):
            result = run_full_investigation(order_id)
            if "error" in result:
                st.error(result["error"])
                return
            st.session_state.customer_gen_result = result

    if "customer_gen_result" in st.session_state and st.session_state.customer_gen_result:
        result = st.session_state.customer_gen_result
        order = result["investigation"]["order"]
        customer_response = result["customer_response"]
        sla = result["sla"]
        diagnostics = result["diagnostics"]

        st.divider()

        info_cols = st.columns(4)
        with info_cols[0]:
            st.metric("Order ID", order["order_id"])
        with info_cols[1]:
            st.metric("Customer", order["customer_name"])
        with info_cols[2]:
            st.metric("SLA Status", sla["sla_status"])
        with info_cols[3]:
            st.metric("Issue", diagnostics["failure_category"] if diagnostics["has_issues"] else "None")

        st.divider()

        st.markdown("#### Generated Customer Response")

        st.text_area(
            "Message",
            value=customer_response["message"],
            height=350,
            key="customer_message_display"
        )

        col_a, col_b, col_c = st.columns(3)
        with col_a:
            st.info(f"**Estimated Resolution:** {customer_response['estimated_resolution']}")
        with col_b:
            st.caption(f"Generated by: {customer_response['generated_by']}")
        with col_c:
            _copy_to_clipboard_button(customer_response["message"])

        st.divider()

        st.markdown("#### Order Context Summary")
        with st.expander("View Investigation Details", expanded=False):
            ctx_cols = st.columns(2)
            with ctx_cols[0]:
                st.markdown("**System Statuses:**")
                st.markdown(f"- Payment: {order['payment_status']}")
                st.markdown(f"- ERP: {order['erp_status']}")
                st.markdown(f"- Fulfillment: {order['fulfillment_status']}")
                st.markdown(f"- Shipment: {order['shipment_status']}")
            with ctx_cols[1]:
                st.markdown("**SLA Details:**")
                st.markdown(f"- Threshold: {order['sla_threshold']} hours")
                st.markdown(f"- Processing: {order['processing_time']} hours")
                st.markdown(f"- Status: {sla['sla_status']}")
                st.markdown(f"- Ratio: {int(sla['ratio'] * 100)}% consumed")

            if diagnostics["has_issues"]:
                st.markdown("**Root Cause:**")
                st.markdown(diagnostics["root_cause"])
